name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  continuous-update:
    name: Continuous update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            args: [--frozen-lockfile]
      - name: Update source code
        run: pnpm update-src
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: continuous-update/${{steps.date.outputs.date}}
          branch-suffix: timestamp
          delete-branch: true
          commit-message: Update on ${{steps.date.outputs.date}}
          title: Continuous update on ${{steps.date.outputs.date}}
          body: |
            Auto-generated by `create-pull-request`[^1].

            [^1]: https://github.com/peter-evans/create-pull-request
          assignees: |
            silver886
          reviewers: |
            silver886
